
swagger: "2.0"

################################################################################
#                              API Information                                 #
#                        http://editor.swagger.io/#!/                          #
################################################################################
info:
  version: "1.0.0"
  title: Rest API
host: localhost:3000
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

################################################################################
#                                 Paths                                        #
################################################################################
paths:
  /signIn:
    x-swagger-router-controller: sign
    post:
      description: Validate the user credentials to access the UI console
      parameters:
        - name: user
          in: body
          description: User credentials
          schema:
            $ref: '#/definitions/User'
          required: true
      tags:
        - Sign
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        200:
          description: User Credentials Matched
  /signUp:
    x-swagger-router-controller: sign
    post:
      description: Register new user to provide access to UI Console
      parameters:
        - name: user
          in: body
          description: User credentials
          schema:
            $ref: '#/definitions/User'
          required: true
      tags:
        - Sign
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        200:
          description: User Registered
          schema:
            $ref: '#/definitions/User'

  /place/create:
    x-swagger-router-controller: place
    post:
      description: Register a new place and create corresponding Topic to publish/subscrible messages.
      parameters:
        - name: place
          in: body
          description: Place co-ordinates and topic
          schema:
            $ref: '#/definitions/Place'
          required: true
      tags:
        - Place
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Place Created
          schema:
            $ref: '#/definitions/Place'

  /place/post:
    x-swagger-router-controller: place
    post:
      description: Publish messages to topic
      parameters:
        - name: message
          in: body
          description: Publish message to topic
          schema:
            $ref: '#/definitions/Message'
          required: true
      tags:
        - Message
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Message Posted
          schema:
            $ref: '#/definitions/Message'

  /place/receive:
    x-swagger-router-controller: place
    post:
      description: Subscribe topic for messages
      parameters:
        - name: subscribe
          in: body
          description: Subscribe topic to messages
          schema:
            $ref: '#/definitions/Subscribe'
          required: true
      tags:
        - Subscribe
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Message Subscribed
          schema:
            $ref: '#/definitions/Subscribe'

  /swagger:
      x-swagger-pipe: swagger_raw

################################################################################
#                                   Models                                     #
################################################################################
definitions:
  Error:
      type: object
      properties:
        message:
          type: string
  User:
    type: object
    properties:
      email:
        type: string
      password:
        type: string

  Place:
    type: object
    properties:
      name:
        type: string
      longitude:
        type: string
      latitude:
        type: string
      createdBy:
        type: string

  Message:
    type: object
    properties:
      queueName:
        type: string
      message:
        type: string
  
  Subscribe:
    type: object
    properties:
      queueName:
        type: string
           